Add link resource
azranel/shareguru-elixir pull request #5
Opened 2016-07-27 07:20 UTC by mwsteb

2016-07-27 07:20 UTC, mwsteb commented
@azranel ready for review!

2016-07-27 12:15 UTC, azranel commented
Could you merge master and add `belongs_to :user, Shareguru.User` (or smth like that) to Shareguru.Link resource? 😄

2016-09-20 18:24 UTC, azranel commented
LGTM

2016-09-20 18:30 UTC, mwsteb commented
@azranel  should be cool now

2016-09-21 12:11 UTC, azranel commented on test/controllers/link_controller_test.exs
> +    |> get(link_path(conn, :index))
This assigning could be extracted to ConnCase 😄

2016-09-21 12:12 UTC, azranel requested changes

2016-09-21 13:26 UTC, azranel approved these changes

2016-09-21 13:27 UTC, merged